### ISSUE TITLE
LineBuffer.format() can't handle "$"

### ISSUE THREAD

**Issue by R3dst0ne** [logisim-evolution/logisim-evolution#1097]
When trying to insert "$" with the help of `LineBuffer.format()` the following exception gets thrown.
> Exception in thread "Thread-2" java.lang.IllegalArgumentException: Illegal group reference: group index is missing
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1029)
        at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
        at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)
        at java.base/java.lang.String.replaceAll(String.java:2142)
        at com.cburch.logisim.util.LineBuffer.applyPairs(LineBuffer.java:350)
        at com.cburch.logisim.util.LineBuffer.format(LineBuffer.java:597)

reproduce:
- use `LineBuffer.format("{{1}}", "$");`

**Comment by MarcinOrlowski** [comment]
@R3dst0ne fixed in #1098
