### ISSUE TITLE
【bug】 when open specified folder as export, logisim crashes

### ISSUE THREAD

**Issue by darallium** [logisim-evolution/logisim-evolution#2025]
case: 
opening "Recently opened files" folder as export, export images, or something else, logisim crashes.

the error log is below.
```
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
        at java.desktop/javax.swing.JFileChooser.showDialog(JFileChooser.java:771)
        at com.cburch.logisim.gui.main.ExportImage.doExport(ExportImage.java:133)
        at com.cburch.logisim.gui.menu.MainMenuListener$FileListener.actionPerformed(MainMenuListener.java:59)
        at com.cburch.logisim.gui.menu.MenuItemHelper.actionPerformed(MenuItemHelper.java:45)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
        at java.desktop/java.awt.Component.processEvent(Component.java:6386)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by maehne** [comment]
Sorry, but your description is not detailed enough to enable me to reproduce your issue. Please answer the following questions:

- What operating system including version are you using? On which CPU platform?
- How did you install Logisim-evolution? Which package type did you use including the exact version? Please provide a URL to that package.
- Does the problem occur with the [latest Nightly Build](https://github.com/logisim-evolution/logisim-evolution/actions/runs/9688432938)? We recommend to use a native installer package, which includes a matching stripped-down JDK for running Logisim-evolution.
- In case you are directly executing the JAR file, please provide the JDK version. Make sure that you have a full JDK installed, e.g. from the [Eclipse Temurin](https://adoptium.net/de/temurin/releases/) project!
- If the problem still occurs, please provide detailed steps on how to trigger the issue.
- If not, please confirm that you were able to resolve the issue on your side and state what the problem was in case others should stumple on it.

**Comment by maehne** [comment]
Thanks for providing the information. I never observed a problem opening recently used `.circ` files using File -> Open Recent -> [file name] as long as the file still exists at the destination. Otherwise, I obtain an error window with an explaining message.

**Comment by davidhutchens** [comment]
From the top lines of the Java method trace, the problem may be that the program does not have sufficient read or write access to the directories or files that you have asked it to use. Could you double check that they should be readable and writable by the program? Could you check if it also fails elsewhere in the file system where you know you have full access?

**Comment by darallium** [comment]
I found out later. I found a Java VM bug similar to this in the bug tracker. It seems that this was an exception that occurs when loading icons.
