### ISSUE TITLE
Combinational Analysis: IllegalArgumentException if only one input and one output are defined

### ISSUE THREAD

**Issue by maehne** [logisim-evolution/logisim-evolution#578]
If one adds only one input variable and one output variable in the `Combinational Analysis` window then clicking on `Minimized` will throw a `java.lang.IllegalArgumentException: Can't add attribute to 0-length text`:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/1174243/119003983-7424de80-b98e-11eb-99ad-6eba2c12e5b3.png">

This is the full stack trace:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Can't add attribute to 0-length text
        at java.base/java.text.AttributedString.addAttribute(AttributedString.java:322)
        at com.cburch.logisim.analyze.gui.KarnaughMapPanel.Styled(KarnaughMapPanel.java:667)
        at com.cburch.logisim.analyze.gui.KarnaughMapPanel.Styled(KarnaughMapPanel.java:676)
        at com.cburch.logisim.analyze.gui.KarnaughMapPanel.drawNumberedHeader(KarnaughMapPanel.java:623)
        at com.cburch.logisim.analyze.gui.KarnaughMapPanel.paintKmap(KarnaughMapPanel.java:522)
        at com.cburch.logisim.analyze.gui.KarnaughMapPanel.paintComponent(KarnaughMapPanel.java:476)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5264)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5212)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5022)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The error occurs on the current HEAD of branch develop, i.e., commit 32152c1524d81c2d5a62142eee92fa9d27c24533.

**Comment by maehne** [comment]
Closing since PR #615 addressing this issue got merged.
